---
- name: Create Consul service definition
  include_role: name=infra-role-consul-service
  vars:
    consul_config_name: '{{ kibana_cont_name }}'
    consul_services:
      - name: '{{ kibana_cont_name }}'
        tags: ['logging']
        # we advertise the port with basic auth
        port: '{{ kibana_cont_port }}'
        checks:
          - id: kibana-status
            name: Kibana Healthcheck
            type: http
            http: 'http://localhost:{{ kibana_cont_port }}/api/status'
