---
- name: 'Create compose file'
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ kibana_compose_path }}'
    owner: dockremap
    group: docker
    mode: 0644

- name: 'Create containers'
  community.docker.docker_compose_v2:
    project_src: '{{ kibana_service_path }}'
    pull:        '{{ compose_pull }}'
    state:       '{{ compose_state }}'
    recreate:    '{{ compose_recreate }}'
