---
- name: 'Create compose file'
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ kibana_compose_path }}'
    owner: dockremap
    group: docker
    mode: 0644

- name: 'Create containers'
  docker_compose:
    project_src: '{{ kibana_service_path }}'
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: '{{ kibana_config.changed | ternary("always", compose_recreate) }}'
    pull: true
    build: false
